# Generated by Django 3.2.6 on 2021-11-06 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a217f518-2299-4a12-a861-0300b6b5a0db'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('admin', 'admin'), ('teacher', 'teacher'), ('student', 'student'), ('guest', 'guest')], max_length=100)),
            ],
        ),
    ]
