# Generated by Django 3.2.6 on 2021-11-06 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manageUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18f7e9aa-6003-472e-8d23-070477dbd25d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
