# Generated by Django 3.2.6 on 2021-11-10 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manageUser', '0002_auto_20211106_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c75b518-df71-43a1-9fe8-2c30092acb09'), editable=False, primary_key=True, serialize=False),
        ),
    ]
